In [58]:
import pandas as pd
import numpy as np
import sklearn

In [59]:
data=pd.read_csv("CarData.csv",encoding="latin1")
data[["Engines","Fuel Types"]]

                                 Engines               Fuel Types
0                                     V8          plug in hyrbrid
1                                    V12                   Petrol
2                            1.2L Petrol                   Petrol
3                                     V8                   Petrol
4                                    V10                   Petrol
...                                  ...                      ...
1213                      2.5L Hybrid I4  Hybrid (Gas + Electric)
1214  2.4L Turbo I4 (i-FORCE MAX Hybrid)                   Hybrid
1215              2.0L Gas / 2.0L Hybrid             Gas / Hybrid
1216                  1.8L / 2.0L Hybrid                   Hybrid
1217        2.5L Hybrid / Plug-in Hybrid         Hybrid / Plug-in

[1218 rows x 2 columns]

In [60]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [61]:
encoder=OneHotEncoder()
label_encoder=LabelEncoder()

In [62]:
encoded_company_names=encoder.fit_transform(data[["Company Names"]]).toarray().astype(int)
encoded_company_names
encoded_company_names_dataFrame=pd.DataFrame(encoded_company_names,columns=encoder.get_feature_names_out())
updated_data=pd.concat([data,encoded_company_names_dataFrame],axis=1)
copy=updated_data.copy()

In [63]:
updated_data.drop("Company Names",axis=1,inplace=True)

In [64]:
updated_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Cars Names                       1218 non-null   object
 1   Engines                          1218 non-null   object
 2   CC/Battery Capacity              1215 non-null   object
 3   HorsePower                       1218 non-null   object
 4   Total Speed                      1218 non-null   object
 5   Performance(0 - 100 )KM/H        1212 non-null   object
 6   Cars Prices                      1218 non-null   object
 7   Fuel Types                       1218 non-null   object
 8   Seats                            1218 non-null   object
 9   Torque                           1217 non-null   object
 10  Company Names_ASTON MARTIN       1218 non-null   int64
 11  Company Names_AUDI               1218 non-null   int64
 12  Company Names_Acura              1218 non-null   int64
 13  Company Names_BENTLEY            1218 non-null   int64
 14  Company Names_BMW                1218 non-null   int64
 15  Company Names_Bugatti            1218 non-null   int64
 16  Company Names_Cadillac           1218 non-null   int64
 17  Company Names_Chevrolet          1218 non-null   int64
 18  Company Names_FERRARI            1218 non-null   int64
 19  Company Names_Ford               1218 non-null   int64
 20  Company Names_GMC                1218 non-null   int64
 21  Company Names_HONDA              1218 non-null   int64
 22  Company Names_HYUNDAI            1218 non-null   int64
 23  Company Names_Jaguar Land Rover  1218 non-null   int64
 24  Company Names_Jeep               1218 non-null   int64
 25  Company Names_KIA                1218 non-null   int64
 26  Company Names_KIA                1218 non-null   int64
 27  Company Names_Kia                1218 non-null   int64
 28  Company Names_LAMBORGHINI        1218 non-null   int64
 29  Company Names_MAHINDRA           1218 non-null   int64
 30  Company Names_MARUTI SUZUKI      1218 non-null   int64
 31  Company Names_MERCEDES           1218 non-null   int64
 32  Company Names_Mazda              1218 non-null   int64
 33  Company Names_Mitsubishi         1218 non-null   int64
 34  Company Names_NISSAN             1218 non-null   int64
 35  Company Names_Nissan             1218 non-null   int64
 36  Company Names_Peugeot            1218 non-null   int64
 37  Company Names_Porsche            1218 non-null   int64
 38  Company Names_ROLLS ROYCE        1218 non-null   int64
 39  Company Names_ROLLS ROYCE        1218 non-null   int64
 40  Company Names_TOYOTA             1218 non-null   int64
 41  Company Names_Tata Motors        1218 non-null   int64
 42  Company Names_Tesla              1218 non-null   int64
 43  Company Names_Toyota             1218 non-null   int64
 44  Company Names_VOLVO              1218 non-null   int64
 45  Company Names_Volkswagen         1218 non-null   int64
 46  Company Names_Volvo              1218 non-null   int64
dtypes: int64(37), object(10)
memory usage: 447.4+ KB

In [65]:
encoded_car_names=label_encoder.fit_transform(data[["Cars Names"]]).astype(int)
encoded_car_names
updated_data["Car_names_encoded"]=encoded_car_names
updated_data.drop("Cars Names",axis=1,inplace=True)
updated_data

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,...,Company Names_ROLLS ROYCE,Company Names_ROLLS ROYCE,Company Names_TOYOTA,Company Names_Tata Motors,Company Names_Tesla,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded
0,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm,0,...,0,0,0,0,0,0,0,0,0,889
1,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm,0,...,1,0,0,0,0,0,0,0,0,741
2,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm,0,...,0,0,0,0,0,0,0,0,0,611
3,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm,0,...,0,0,0,0,0,0,0,0,0,0
4,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm,0,...,0,0,0,0,0,0,0,0,0,139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,2487 cc,240 hp,180 km/h,7.6 sec,"$43,590 Â– $48,000",Hybrid (Gas + Electric),5,239 Nm,0,...,0,0,0,0,0,1,0,0,0,350
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),2393 cc + Battery,326 hp,180 km/h,6.8 sec,"$50,000",Hybrid,7,630 Nm,0,...,0,0,0,0,0,1,0,0,0,67
1215,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169 Â– 196 hp,190 km/h,8.0 Â– 9.2 sec,"$25,210 Â– $29,135",Gas / Hybrid,5,190 Â– 210 Nm,0,...,0,0,0,0,0,1,0,0,0,342
1216,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140 Â– 198 hp,180 km/h,7.9 Â– 10.5 sec,"Â€ 33,000",Hybrid,5,190 Â– 205 Nm,0,...,0,0,0,0,0,1,0,0,0,241
1217,2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219 Â– 302 hp,200 km/h,6.0 Â– 8.1 sec,"$29,000 Â– $43,000",Hybrid / Plug-in,5,221 Â– 400 Nm,0,...,0,0,0,0,0,1,0,0,0,843

In [66]:
updated_data["CC/Batery_capasity_encoded"]=updated_data["CC/Battery Capacity"].str.split(" ").str[0]

In [67]:
updated_data["CC/Batery_capasity_encoded"]=(updated_data["CC/Batery_capasity_encoded"].astype(str).str.replace(r"[^0-9]","",regex=True).replace("",None).astype(float))

In [68]:
updated_data["CC/Batery_capasity_encoded"]=(updated_data["CC/Batery_capasity_encoded"].fillna(updated_data["CC/Batery_capasity_encoded"].mean()))

In [69]:
updated_data["CC/Batery_capasity_encoded"].mean()

np.float64(2767.179190751445)

In [70]:
updated_data.drop("CC/Battery Capacity",axis=1,inplace=True)

In [71]:
updated_data

,Engines,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,...,Company Names_ROLLS ROYCE,Company Names_TOYOTA,Company Names_Tata Motors,Company Names_Tesla,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded
0,V8,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm,0,0,...,0,0,0,0,0,0,0,0,889,3990.0
1,V12,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm,0,0,...,0,0,0,0,0,0,0,0,741,6749.0
2,1.2L Petrol,70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm,0,0,...,0,0,0,0,0,0,0,0,611,1200.0
3,V8,630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm,0,0,...,0,0,0,0,0,0,0,0,0,3982.0
4,V10,602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm,0,1,...,0,0,0,0,0,0,0,0,139,5204.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,240 hp,180 km/h,7.6 sec,"$43,590 Â– $48,000",Hybrid (Gas + Electric),5,239 Nm,0,0,...,0,0,0,0,1,0,0,0,350,2487.0
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),326 hp,180 km/h,6.8 sec,"$50,000",Hybrid,7,630 Nm,0,0,...,0,0,0,0,1,0,0,0,67,2393.0
1215,2.0L Gas / 2.0L Hybrid,169 Â– 196 hp,190 km/h,8.0 Â– 9.2 sec,"$25,210 Â– $29,135",Gas / Hybrid,5,190 Â– 210 Nm,0,0,...,0,0,0,0,1,0,0,0,342,1987.0
1216,1.8L / 2.0L Hybrid,140 Â– 198 hp,180 km/h,7.9 Â– 10.5 sec,"Â€ 33,000",Hybrid,5,190 Â– 205 Nm,0,0,...,0,0,0,0,1,0,0,0,241,1798.0
1217,2.5L Hybrid / Plug-in Hybrid,219 Â– 302 hp,200 km/h,6.0 Â– 8.1 sec,"$29,000 Â– $43,000",Hybrid / Plug-in,5,221 Â– 400 Nm,0,0,...,0,0,0,0,1,0,0,0,843,2487.0

In [72]:
updated_data["HorsePower"]

0             963 hp
1             563 hp
2           70-85 hp
3             630 hp
4             602 hp
            ...
1213          240 hp
1214          326 hp
1215    169 Â– 196 hp
1216    140 Â– 198 hp
1217    219 Â– 302 hp
Name: HorsePower, Length: 1218, dtype: object

In [73]:
import re
def clean_hp(value):
    if pd.isna(value):
        return None
    numbers=re.findall(r"\d+",str(value))
    if not numbers:
        return None
    if len(numbers)==2:
        return (int(numbers[0])+int(numbers[1]))/2
    return int(numbers[0])
updated_data["Hp_encoded"]=updated_data["HorsePower"].apply(clean_hp)
updated_data["Hp_encoded"]

0       963.0
1       563.0
2        77.5
3       630.0
4       602.0
        ...
1213    240.0
1214    326.0
1215    182.5
1216    169.0
1217    260.5
Name: Hp_encoded, Length: 1218, dtype: float64

In [74]:
updated_data.drop("HorsePower",axis=1,inplace=True)

In [75]:
updated_data

,Engines,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,...,Company Names_TOYOTA,Company Names_Tata Motors,Company Names_Tesla,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded
0,V8,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm,0,0,0,...,0,0,0,0,0,0,0,889,3990.0,963.0
1,V12,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm,0,0,0,...,0,0,0,0,0,0,0,741,6749.0,563.0
2,1.2L Petrol,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm,0,0,0,...,0,0,0,0,0,0,0,611,1200.0,77.5
3,V8,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm,0,0,0,...,0,0,0,0,0,0,0,0,3982.0,630.0
4,V10,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm,0,1,0,...,0,0,0,0,0,0,0,139,5204.0,602.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,180 km/h,7.6 sec,"$43,590 Â– $48,000",Hybrid (Gas + Electric),5,239 Nm,0,0,0,...,0,0,0,1,0,0,0,350,2487.0,240.0
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),180 km/h,6.8 sec,"$50,000",Hybrid,7,630 Nm,0,0,0,...,0,0,0,1,0,0,0,67,2393.0,326.0
1215,2.0L Gas / 2.0L Hybrid,190 km/h,8.0 Â– 9.2 sec,"$25,210 Â– $29,135",Gas / Hybrid,5,190 Â– 210 Nm,0,0,0,...,0,0,0,1,0,0,0,342,1987.0,182.5
1216,1.8L / 2.0L Hybrid,180 km/h,7.9 Â– 10.5 sec,"Â€ 33,000",Hybrid,5,190 Â– 205 Nm,0,0,0,...,0,0,0,1,0,0,0,241,1798.0,169.0
1217,2.5L Hybrid / Plug-in Hybrid,200 km/h,6.0 Â– 8.1 sec,"$29,000 Â– $43,000",Hybrid / Plug-in,5,221 Â– 400 Nm,0,0,0,...,0,0,0,1,0,0,0,843,2487.0,260.5

In [76]:
updated_data["Speed_encoded"]=updated_data["Total Speed"].str.split(" ").str[0]
updated_data["Speed_encoded"]=updated_data["Speed_encoded"].astype(int)

In [77]:
updated_data.drop("Total Speed",axis=1,inplace=True)

In [78]:
updated_data

,Engines,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,...,Company Names_Tata Motors,Company Names_Tesla,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded,Speed_encoded
0,V8,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm,0,0,0,0,...,0,0,0,0,0,0,889,3990.0,963.0,340
1,V12,5.3 sec,"$460,000",Petrol,5,900 Nm,0,0,0,0,...,0,0,0,0,0,0,741,6749.0,563.0,250
2,1.2L Petrol,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm,0,0,0,0,...,0,0,0,0,0,0,611,1200.0,77.5,165
3,V8,3.2 sec,"$161,000",Petrol,4,900 Nm,0,0,0,0,...,0,0,0,0,0,0,0,3982.0,630.0,250
4,V10,3.6 sec,"$253,290",Petrol,2,560 Nm,0,1,0,0,...,0,0,0,0,0,0,139,5204.0,602.0,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,7.6 sec,"$43,590 Â– $48,000",Hybrid (Gas + Electric),5,239 Nm,0,0,0,0,...,0,0,1,0,0,0,350,2487.0,240.0,180
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),6.8 sec,"$50,000",Hybrid,7,630 Nm,0,0,0,0,...,0,0,1,0,0,0,67,2393.0,326.0,180
1215,2.0L Gas / 2.0L Hybrid,8.0 Â– 9.2 sec,"$25,210 Â– $29,135",Gas / Hybrid,5,190 Â– 210 Nm,0,0,0,0,...,0,0,1,0,0,0,342,1987.0,182.5,190
1216,1.8L / 2.0L Hybrid,7.9 Â– 10.5 sec,"Â€ 33,000",Hybrid,5,190 Â– 205 Nm,0,0,0,0,...,0,0,1,0,0,0,241,1798.0,169.0,180
1217,2.5L Hybrid / Plug-in Hybrid,6.0 Â– 8.1 sec,"$29,000 Â– $43,000",Hybrid / Plug-in,5,221 Â– 400 Nm,0,0,0,0,...,0,0,1,0,0,0,843,2487.0,260.5,200

In [79]:
def format_performance(value):
    if pd.isna(value):
        return None
    performance=re.findall(r"\d+\.?\d*",str(value))
    if not performance:
        return None
    if len(performance)==2:
        return (float(performance[0])+float(performance[1]))/2
    return float(performance[0])
updated_data["performance_encoded"]=updated_data["Performance(0 - 100 )KM/H"].apply(format_performance)

In [80]:
updated_data.head(1)
updated_data.drop("Performance(0 - 100 )KM/H",axis=1,inplace=True)

In [81]:
updated_data.head(1)

,Engines,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,...,Company Names_Tesla,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded,Speed_encoded,performance_encoded
0,V8,"$1,100,000",plug in hyrbrid,2,800 Nm,0,0,0,0,0,...,0,0,0,0,0,889,3990.0,963.0,340,2.5

In [82]:
updated_data["Cars Prices"]

0             $1,100,000
1               $460,000
2         $12,000-$15,000
3               $161,000
4               $253,290
              ...
1213    $43,590 Â– $48,000
1214             $50,000
1215    $25,210 Â– $29,135
1216             Â€ 33,000
1217    $29,000 Â– $43,000
Name: Cars Prices, Length: 1218, dtype: object

In [83]:
def clean_price(value):
    if pd.isna(value):
        return None
    text=str(value)
    text=text.replace("â‚¬","").replace("$","")
    text = text.replace("Â–", "-")       # fix special dash
    text = text.strip()       
    numbers = re.findall(r"[0-9,]+", str(text))
    numbers=[float(num.replace(",",""))for num in numbers]
    if not numbers:
        return None
    if len(numbers)==2:
        return sum(numbers)/2
    return numbers[0]

In [84]:
updated_data["cleaned_Car_prices"]=updated_data["Cars Prices"].apply(clean_price)

In [85]:
updated_data

,Engines,Cars Prices,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,...,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded,Speed_encoded,performance_encoded,cleaned_Car_prices
0,V8,"$1,100,000",plug in hyrbrid,2,800 Nm,0,0,0,0,0,...,0,0,0,0,889,3990.0,963.0,340,2.50,1100000.0
1,V12,"$460,000",Petrol,5,900 Nm,0,0,0,0,0,...,0,0,0,0,741,6749.0,563.0,250,5.30,460000.0
2,1.2L Petrol,"$12,000-$15,000",Petrol,5,100 - 140 Nm,0,0,0,0,0,...,0,0,0,0,611,1200.0,77.5,165,10.50,13500.0
3,V8,"$161,000",Petrol,4,900 Nm,0,0,0,0,0,...,0,0,0,0,0,3982.0,630.0,250,3.20,161000.0
4,V10,"$253,290",Petrol,2,560 Nm,0,1,0,0,0,...,0,0,0,0,139,5204.0,602.0,320,3.60,253290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,"$43,590 Â– $48,000",Hybrid (Gas + Electric),5,239 Nm,0,0,0,0,0,...,1,0,0,0,350,2487.0,240.0,180,7.60,45795.0
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),"$50,000",Hybrid,7,630 Nm,0,0,0,0,0,...,1,0,0,0,67,2393.0,326.0,180,6.80,50000.0
1215,2.0L Gas / 2.0L Hybrid,"$25,210 Â– $29,135",Gas / Hybrid,5,190 Â– 210 Nm,0,0,0,0,0,...,1,0,0,0,342,1987.0,182.5,190,8.60,27172.5
1216,1.8L / 2.0L Hybrid,"Â€ 33,000",Hybrid,5,190 Â– 205 Nm,0,0,0,0,0,...,1,0,0,0,241,1798.0,169.0,180,9.20,33000.0
1217,2.5L Hybrid / Plug-in Hybrid,"$29,000 Â– $43,000",Hybrid / Plug-in,5,221 Â– 400 Nm,0,0,0,0,0,...,1,0,0,0,843,2487.0,260.5,200,7.05,36000.0

In [86]:
updated_data.drop("Cars Prices",axis=1,inplace=True)

In [87]:
updated_data

,Engines,Fuel Types,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,...,Company Names_Toyota,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded,Speed_encoded,performance_encoded,cleaned_Car_prices
0,V8,plug in hyrbrid,2,800 Nm,0,0,0,0,0,0,...,0,0,0,0,889,3990.0,963.0,340,2.50,1100000.0
1,V12,Petrol,5,900 Nm,0,0,0,0,0,0,...,0,0,0,0,741,6749.0,563.0,250,5.30,460000.0
2,1.2L Petrol,Petrol,5,100 - 140 Nm,0,0,0,0,0,0,...,0,0,0,0,611,1200.0,77.5,165,10.50,13500.0
3,V8,Petrol,4,900 Nm,0,0,0,0,0,0,...,0,0,0,0,0,3982.0,630.0,250,3.20,161000.0
4,V10,Petrol,2,560 Nm,0,1,0,0,0,0,...,0,0,0,0,139,5204.0,602.0,320,3.60,253290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,Hybrid (Gas + Electric),5,239 Nm,0,0,0,0,0,0,...,1,0,0,0,350,2487.0,240.0,180,7.60,45795.0
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),Hybrid,7,630 Nm,0,0,0,0,0,0,...,1,0,0,0,67,2393.0,326.0,180,6.80,50000.0
1215,2.0L Gas / 2.0L Hybrid,Gas / Hybrid,5,190 Â– 210 Nm,0,0,0,0,0,0,...,1,0,0,0,342,1987.0,182.5,190,8.60,27172.5
1216,1.8L / 2.0L Hybrid,Hybrid,5,190 Â– 205 Nm,0,0,0,0,0,0,...,1,0,0,0,241,1798.0,169.0,180,9.20,33000.0
1217,2.5L Hybrid / Plug-in Hybrid,Hybrid / Plug-in,5,221 Â– 400 Nm,0,0,0,0,0,0,...,1,0,0,0,843,2487.0,260.5,200,7.05,36000.0

In [88]:
updated_data["Fuel Types"].unique()

array(['plug in hyrbrid', 'Petrol', 'Diesel', 'Hybrid', 'Electric',
       'Petrol/Diesel', 'Plug-in Hybrid', 'Petrol/AWD', 'Petrol/Hybrid',
       'Hydrogen', 'Diesel/Petrol', 'Petrol/EV', 'Hybrid/Electric',
       'Petrol, Hybrid', 'Petrol, Diesel', 'Hybrid (Petrol)',
       'CNG/Petrol', 'Hybrid/Petrol', 'Diesel Hybrid', 'Petrol (Hybrid)',
       'Hybrid (Gas + Electric)', 'Gas / Hybrid', 'Hybrid / Plug-in'],
      dtype=object)

In [89]:
def clean_fuels(values):
    text=str(values).lower().strip()

    text=text.replace(",","/").replace("+","/").replace("(","").replace(")","").replace("/","").replace("-","")
    text=text.replace(" ","")
    text=text.replace("hyrbrid","hybrid")
     # standardize common terms
    text = text.replace("plug-inhybrid", "plugin-hybrid")
    text = text.replace("hybrid/petrol", "petrol-hybrid")
    text = text.replace("petrolhybrid", "petrol-hybrid")
    text = text.replace("dieselhybrid", "diesel-hybrid")
    text = text.replace("hybrid/gaselectric", "hybrid-electric")
    text=text.replace("plugin-hybrid","pluginhybrid")
    text=text.replace("hybrid/plug-in","hybridplug-in")  
    text=text.replace("gas/hybrid","gashybrid")  
    text=text.replace("petrol-hybrid","petrolhybrid")  
    text=text.replace("cng/petrol","cngpetrol")  
    text=text.replace("hybridgas/electric","hybridgaselectric")  
    text=text.replace("diesel-hybrid","dieselhybrid")
    return text

In [90]:
updated_data["Clean_fuels"]=updated_data["Fuel Types"].apply(clean_fuels)

In [91]:
updated_data["Clean_fuels"].unique()

array(['pluginhybrid', 'petrol', 'diesel', 'hybrid', 'electric',
       'petroldiesel', 'petrolawd', 'petrolhybrid', 'hydrogen',
       'dieselpetrol', 'petrolev', 'hybridelectric', 'hybridpetrol',
       'cngpetrol', 'dieselhybrid', 'hybridgaselectric', 'gashybrid',
       'hybridplugin'], dtype=object)

In [92]:
sorted(updated_data["Clean_fuels"].unique())

['cngpetrol',
 'diesel',
 'dieselhybrid',
 'dieselpetrol',
 'electric',
 'gashybrid',
 'hybrid',
 'hybridelectric',
 'hybridgaselectric',
 'hybridpetrol',
 'hybridplugin',
 'hydrogen',
 'petrol',
 'petrolawd',
 'petroldiesel',
 'petrolev',
 'petrolhybrid',
 'pluginhybrid']

In [93]:
updated_data.drop("Fuel Types",axis=1,inplace=True)

In [94]:
updated_data

,Engines,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,...,Company Names_VOLVO,Company Names_Volkswagen,Company Names_Volvo,Car_names_encoded,CC/Batery_capasity_encoded,Hp_encoded,Speed_encoded,performance_encoded,cleaned_Car_prices,Clean_fuels
0,V8,2,800 Nm,0,0,0,0,0,0,0,...,0,0,0,889,3990.0,963.0,340,2.50,1100000.0,pluginhybrid
1,V12,5,900 Nm,0,0,0,0,0,0,0,...,0,0,0,741,6749.0,563.0,250,5.30,460000.0,petrol
2,1.2L Petrol,5,100 - 140 Nm,0,0,0,0,0,0,0,...,0,0,0,611,1200.0,77.5,165,10.50,13500.0,petrol
3,V8,4,900 Nm,0,0,0,0,0,0,0,...,0,0,0,0,3982.0,630.0,250,3.20,161000.0,petrol
4,V10,2,560 Nm,0,1,0,0,0,0,0,...,0,0,0,139,5204.0,602.0,320,3.60,253290.0,petrol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,5,239 Nm,0,0,0,0,0,0,0,...,0,0,0,350,2487.0,240.0,180,7.60,45795.0,hybridgaselectric
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),7,630 Nm,0,0,0,0,0,0,0,...,0,0,0,67,2393.0,326.0,180,6.80,50000.0,hybrid
1215,2.0L Gas / 2.0L Hybrid,5,190 Â– 210 Nm,0,0,0,0,0,0,0,...,0,0,0,342,1987.0,182.5,190,8.60,27172.5,gashybrid
1216,1.8L / 2.0L Hybrid,5,190 Â– 205 Nm,0,0,0,0,0,0,0,...,0,0,0,241,1798.0,169.0,180,9.20,33000.0,hybrid
1217,2.5L Hybrid / Plug-in Hybrid,5,221 Â– 400 Nm,0,0,0,0,0,0,0,...,0,0,0,843,2487.0,260.5,200,7.05,36000.0,hybridplugin

In [95]:
fuel_modified=encoder.fit_transform(updated_data[["Clean_fuels"]]).toarray().astype(int)

In [96]:
fuel_df=pd.DataFrame(fuel_modified,columns=encoder.get_feature_names_out())

In [97]:
updated_data=pd.concat([updated_data,fuel_df],axis=1)

In [98]:
updated_data.tail(5)

,Engines,Seats,Torque,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,...,Clean_fuels_hybridgaselectric,Clean_fuels_hybridpetrol,Clean_fuels_hybridplugin,Clean_fuels_hydrogen,Clean_fuels_petrol,Clean_fuels_petrolawd,Clean_fuels_petroldiesel,Clean_fuels_petrolev,Clean_fuels_petrolhybrid,Clean_fuels_pluginhybrid
1213,2.5L Hybrid I4,5,239 Nm,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),7,630 Nm,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1215,2.0L Gas / 2.0L Hybrid,5,190 Â– 210 Nm,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1216,1.8L / 2.0L Hybrid,5,190 Â– 205 Nm,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1217,2.5L Hybrid / Plug-in Hybrid,5,221 Â– 400 Nm,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [99]:
def cleaned_torque(values):
    text=str(values).replace("Nm","").replace("Â–","-").strip()

    parts=text.split("-")
    text=text.split(" ")
    try:
        if len(parts)==2:
            return (int(parts[0])+int(parts[1]))/2
        return int(parts[0])
    except:
        return None
updated_data["New Torque"]=updated_data["Torque"].apply(cleaned_torque)

In [100]:
updated_data["New Torque"].tail()

1213    239.0
1214    630.0
1215    200.0
1216    197.5
1217    310.5
Name: New Torque, dtype: float64

In [101]:
updated_data.drop("Torque",axis=1,inplace=True)

In [102]:
updated_data["Seats"]=pd.to_numeric(updated_data["Seats"],errors="coerce")

In [103]:
updated_data["Seats"].isnull().sum()
updated_data["Seats"]=updated_data["Seats"].fillna(updated_data["Seats"].mean())

In [104]:
updated_data["Seats"].isnull().sum()

np.int64(0)

In [105]:
updated_data["Seats"]=updated_data["Seats"].astype(int)

In [106]:
updated_data["Seats"]

0       2
1       5
2       5
3       4
4       2
       ..
1213    5
1214    7
1215    5
1216    5
1217    5
Name: Seats, Length: 1218, dtype: int64

In [107]:
updated_data["Engines"].unique()

array(['V8', 'V12', '1.2L Petrol', 'V10', 'I4', 'BOXER-4', 'V6',
       'ELECTRIC MOTOR', 'I6', 'ELECTRIC ', 'ELECTRIC', 'I3',
       'I4 + ELECTRIC', 'HYBRID', '1.2L,4-CYLINDER,INLINE-4(I4)',
       '1.4L,4-CYLINDER,INLINE-4(I4)', '2.0L,4-CYLINDER,INLINE-4(I4)',
       '2.2L,4-CYLINDER,INLINE-4(I4)', '1.5L,4-CYLINDER,INLINE(I4)',
       '2.0L,4-CYLINDER,WITH HYBRID SYSTEM', '1.6L,TURBOCHARGED INLINE-3',
       '3.3L,V6,TWIN TURBO DIESEL', '3.5L,V6,HYBRID TWIN-TURBO',
       '2.0L,INLINE-4', 'HYDROGEN FUEL CELL,ELECTRIC MOTOR',
       '2.8L,TURBO,DIESEL', '2.5L,INLINE-4,HYBRID,OR 3.5L,V6',
       '2.0L HYBRID', '4.0L,DIESEL', '1.5L,HYBRID', '1.0L,INLINE-3',
       '3.5L,V6,PLUG IN HYBRID', '1.8L,HYBRID',
       '1.6L PETROL + PLUG IN HYBRID SYSTEM',
       '2.5L Turbocharged Inline-4', '1.6L PETROL ', '2.0L Inline-4',
       '2.5L Turbo Diese', 'Electric Motor', '2.5L Inline-4', '3.8L V6',
       '1.6L Inline-4', '3.3L V6', '1.6L Turbo GDI 4-cylinder',
       '1.5L Turbo I4 / Electric', '2.0L Turbo I4', '1.5L Turbo I4',
       '1.0L Turbo I3 / 1.6L Diesel', 'Electric',
       '3.0L V6 Turbo Diesel / 4.0L V8', '3.0L V6 Turbo Diesel',
       '4.0L V6', '2.0L Turbo Diesel I4', '1.0L Turbo I3',
       '1.0L Turbo I3 / 1.5L Turbo I4', 'Plug-in Hybrid V6',
       'Plug-in Hybrid / Diesel I4', '1.2L Diesel I3', 'Electric AWD',
       '1.5L Turbo I4 / 2.0L Diesel I4', '1.4L I3 Gas / 1.2L Diesel I3',
       '2.9L VR6', '3.0L V6 Diesel / 6.0L W12 Gas',
       '1.2L I4 Turbo / 2.0L I4 Turbo', '1.5L I4 Gas',
       '1.4L I4 Gas / 1.6L I4 Gas', '1.2L I4 Gas',
       '1.2L I4 Gas / 1.4L I4 Gas', '1.6L I4 Gas / Diesel',
       '1.6L I4 Gas / 1.9L I4 Diesel', '2.0L I4 Turbo / 3.6L V6 Gas',
       '1.5L I4 Turbo', '1.0L I3 Turbo', '1.0L I3 Turbo / 1.5L I4 Turbo',
       '2.0L I4 Turbo', '2.0L I4 Turbo Diesel',
       '1.4L I4 Diesel / 1.6L Diesel', 'Plug-in Hybrid (1.4L I4 Turbo)',
       '4.0L V8 Turbo Diesel', '1.4L I4 Turbo',
       '1.5L I4 Turbo / 2.0L Diesel', '1.8L I4 Gas', '3.2L VR6',
       '1.6L Diesel / 2.0L I4 Turbo', '2.0L Diesel I4',
       '1.6L Turbocharged Rally Engine', '1.4L I4 Turbo + Electric Motor',
       'Plug-in Hybrid (0.8L I2 Diesel)', '1.5L I4 CNG',
       '1.4L I4 Turbo / 2.0L Diesel I4',
       '3.0L V6 Turbo Diesel / Gasoline', '1.0L Turbocharged Inline-3',
       '5.6L V8', '1.3L Turbocharged Inline-4', '3.5L V6',
       '1.5L Turbocharged Inline-3', '3.0L Twin-Turbo V6',
       '1.8L Inline-4', '1.2L Inline-3 Hybrid', '1.5L Inline-4 Diesel',
       '3.8L Twin-Turbo V6', '3.7L V6', 'Dual Electric Motors',
       '1.2L Turbocharged Inline-4', '1.5L Inline-4', '1.2L Inline-3',
       '2.0L Inline-4 Hybrid', '3.0L V6 Twin-Turbo', '2.0L Inline-6',
       '2.5L V6', '4.8L Inline-6', '2.5L Inline-4 Hybrid',
       '1.5L Turbo Inline-3', '1.3L Turbo Hybrid Inline-4', '5.0L V8',
       '3.0L V6', '1.6L Turbo Inline-4', '2.4L Inline-4',
       '2.6L Twin-Turbo Inline-6', '2.0L VC-Turbo Inline-4',
       '2.5L Inline-4 Diesel', '2.3L Inline-4 Diesel', '1.4L Inline-4',
       '2.8L Inline-6 Diesel', '2.0L Turbo Inline-4',
       '2.7L Inline-4 Diesel', '1.5L Turbo Hybrid',
       '3.0L Twin-Turbo V6 Hybrid', '3.5L Twin-Turbo V8',
       '1.0L Turbo Inline-4', '3.0L Inline-4 Diesel', '660cc Inline-3',
       '1.5L Hybrid', '4.5L V8', '2.4L Inline-6', '1.2L Hybrid',
       '2.7L Turbo Diesel', '4.2L Inline-6', '4.1L V8', '3.0L V6 Turbo',
       '2.8L Inline-6', '1.8L Turbo Inline-4', '2.9L V6 Twin Turbo',
       '4.0L V8 Twin Turbo', '2.9L V6 + Electric Motor',
       '4.0L V8 + Electric Motor', '3.0L Flat-6 Twin Turbo',
       '3.0L Twin-Turbo Flat-6', '3.8L Twin-Turbo Flat-6',
       '4.0L Naturally Aspirated Flat-6', '2.0L Turbocharged Flat-4',
       '2.5L Turbocharged Flat-4', '2.0L Turbo Flat-4',
       '2.9L Twin-Turbo V6', '2.9L Twin-Turbo V6 + Electric Motor',
       '4.0L Twin-Turbo V8 + Electric Motor', '4.0L Twin-Turbo V8',
       '3.0L Turbocharged V6', '3.0L V6 + Electric Motor',
       '3.0L Turbo Diesel V6', '2.0L Turbo Inline-4 Gasoline',
       '2.7L Turbo Inline-4 Gasoline', '3.0L Twin-Turbo V6 Gasoline',
       '4.2L Naturally Aspirated Flat-6',
       '1.2L Revotron 3-cylinder Petrol', 'Permanent Magnet Synchronous',
       '1.2L Revotron Petrol / 1.5L Diesel', '1.2L Turbocharged Petrol',
       '1.2L Revotron Bi-Fuel', '624cc MPFI', '1.4L CR4 Diesel',
       '1.2L MPFI Petrol', '1.3L Quadrajet Diesel / 1.2L Revotron Petrol',
       '6.2L V8 Gasoline', '1.4L CR4 Diesel / 1.4L Petrol',
       '1.3L Quadrajet Diesel / 1.4L Petrol', '1.4L MPFI Petrol',
       '1.2L Turbo Petrol / 1.5L Diesel',
       '2.0L Kryotec Turbocharged Diesel', '1.2L Revotron Petrol',
       '2.2L Varicor Diesel', '2.2L Dicor Diesel', '3.0L CR4 Diesel',
       'Tri Electric Motors', 'Single Electric Motor (RWD)',
       'Dual Electric Motors (AWD)', 'Quad Electric Motors',
       '3.6L V6 Pentastar Gasoline', '2.0L Turbo I4 Gasoline',
       '2.4L I4 Tigershark Gasoline', '2.0L Turbo Gasoline',
       '1.3L Turbo I4 Gasoline', '5.7L V8 Gasoline with eTorque',
       '6.4L V8 Gasoline', '2.0L Turbo PHEV', '1.3L Turbo PHEV',
       '1.5L 4-Cylinder', '5.7L V8 Gasoline',
       '3.2L V6 Pentastar Gasoline', '6.4L V8 HEMI Gasoline',
       '3.6L V6 Gasoline', 'Single Electric Motor',
       '6.2L Supercharged V8 Gasoline', '3.6L Twin-Turbo V6 Gasoline',
       '1.4L Inline-4 Gasoline', '1.4L Turbo Inline-4 Gasoline',
       '1.5L Turbo Inline-4 Gasoline', '5.3L V8 Gasoline',
       '6.6L V8 Gasoline', '6.6L V8 Diesel',
       '1.3L Turbo Inline-3 Gasoline', '2.8L Turbo Diesel I4',
       '1.2L Turbo Inline-3 Gasoline', '4.3L V6 Gasoline',
       '2.5L Inline-4 Gasoline', '1.5L Turbo 4-cylinder',
       '2.0L Turbo 4-cylinder', '2.7L Turbo 4-cylinder',
       'Dual-Motor Electric', '3.6L V6 engine', '5.3L V8 engine',
       '2.7L Turbo engine', '6.6L V8 engine', '2.5L I4 engine',
       '6.2L V8 engine', '1.5L Turbocharged I4 engine',
       'Electric motors with up to 11,500 lb-ft torque', '4.3L V6 engine',
       'Electric motors with advanced AWD', '1.6L 4-Cylinder',
       '1.6L Turbocharged 4-Cylinder', 'Hybrid I4 + Electric Motor',
       '2.5L Turbocharged 4-Cylinder', '2.0L 4-Cylinder',
       '1.6L 4-Cylinder Hybrid', '1.6L Hybrid Turbocharged 4-Cylinder',
       '2.5L 4-Cylinder', '3.3L Turbocharged V6',
       '2.5L Hybrid Turbocharged 4-Cylinder', 'Hybrid I4+ Electric Motor',
       '8.0L Quad-Turbo W16', '13.0L I6 Turbo Diesel',
       '16.1L I6 Turbo Diesel', '12.8L I6 Turbo Diesel',
       '7.7L I6 Turbo Diesel', '5.1L I4 Turbo Diesel', 'V6 / V8 Petrol',
       'I4 Petrol', 'V6 Petrol', 'Electric (Dual Motor)',
       'I4 Petrol / V6 Petrol', 'V8 Petrol', 'I4 Petrol + Electric Motor',
       'Twin-Turbo V6 Hybrid', 'I4 Turbocharged', 'Inline-4', 'V6 Hybrid',
       'Inline-4 Hybrid', 'Inline-4 Turbocharged', 'Turbocharged I4',
       'Turbocharged V6', 'Diesel I4', 'Hybrid I4',
       '1.5L EcoBoost / 2.0L Hybrid', '3.5L V6 / 2.0L EcoBoost',
       '1.0L EcoBoost / 1.5L', '1.0L EcoBoost / 1.5L / 2.0L',
       '1.0L Turbo Inline-3 / 2.0L', '1.5L EcoBoost / 2.5L Hybrid',
       '2.0L EcoBoost / 2.7L V6', '2.3L EcoBoost / 3.0L V6',
       '3.5L EcoBoost / 5.4L V8', '2.3L EcoBoost / 2.7L V6',
       '1.5L EcoBoost / 2.0L EcoBoost',
       '3.3L V6 / 5.0L V8 / 3.5L EcoBoost',
       '6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel',
       '6.7L Turbo-Diesel / 7.3L V8', '2.5L Hybrid / 2.0L EcoBoost',
       '2.3L Turbo Inline-4 / 2.7L V6', '2.5L Inline-4 + Electric',
       '3.3L V6 + Electric', '3.5L Twin-Turbo V6', '2.3L Turbo Inline-4',
       '2.7L Twin-Turbo V6', 'Turbocharged Inline-3',
       'Turbocharged Inline-4', 'Naturally Aspirated V6',
       'EcoBlue Turbo Diesel', 'Inline-4 Gasoline Engine',
       'Turbocharged V8 Diesel', 'Supercharged V8',
       'Naturally Aspirated V8', 'V8 Gasoline Engine',
       'V6 Hybrid + Electric Motor', 'I4 Hybrid', 'I4 Turbo Diesel',
       'V6 EcoBoost', 'V6 Turbocharged', '1.2L MIVEC', '2.4L Hybrid',
       '1.5L Turbo', '2.0L MIVEC', '3.2L Diesel Turbo',
       '2.4L Diesel Turbo', '2.0L Turbocharged', '1.5L MIVEC',
       '2.2L Diesel Turbo', '1.1L / 1.5L MIVEC', '2.4L MIVEC',
       '1.6L MIVEC / 2.0L', '2.0L Diesel / 2.2L Diesel', '3.0L Diesel',
       '1.6L MIVEC', '2.4L PHEV', '7.5L Diesel', '3.0L Diesel Hybrid',
       '1.8L MIVEC', '0.7L 3-Cylinder', '2.4L Petrol', '2.4L 4-Cylinder',
       '1.5L Turbocharged', '2.0L SkyActiv-G', '2.5L SkyActiv-G',
       '2.5L Turbocharged', '2.2L Diesel', '3.3L Inline-6 Turbo',
       '2.3L Turbocharged', '2.5L Diesel', '3.2L Turbo Diesel',
       '1.3L Rotary Twin-Turbo', '1.2L Rotary', 'Rotary SkyActiv-R',
       '1.5L SkyActiv-G', '2.3L Miller Cycle V6', '2.0L Twin-Rotor Turbo',
       '1.3L Rotary', '1.8L Rotary', '657cc Turbocharged Inline-3',
       '2.6L Inline-4', '3.0L Inline-4', '3.0L Inline-6', '1.3L Inline-4',
       '1.2L Inline-4', '1.3L Inline-2 (Wankel)',
       '1.6L Inline-2 (Wankel)', '1.0L Inline-2 (Wankel)',
       '1.3L Wankel + Electric', '0.36L Inline-2', '0.66L Inline-3',
       '1.3L Wankel Rotary Engine', '2.6L Wankel Rotary Engine',
       '2.5L Hybrid I4', '2.4L Turbo I4 (i-FORCE MAX Hybrid)',
       '2.0L Gas / 2.0L Hybrid', '1.8L / 2.0L Hybrid',
       '2.5L Hybrid / Plug-in Hybrid'], dtype=object)

In [108]:
def clean_engines(values):
    text=str(values).lower().strip()

    #extracting displacement
    displacement_match = re.search(r"(\d+(?:\.\d+)?)\s*l", text)

    if displacement_match:
        displacement=float(displacement_match.group(1))
    else:
        displacement=np.nan

    config_match=re.search(r"(v\d|i\d|boxer-\d|w\d+|wankel|rotary|inline-\d)",text)
    if config_match:
        config=config_match.group(0).upper()
    else:
        config=None
    if "electric" in text:
        powertrain = "Electric"
    elif "hybrid" in text or "plug" in text:
        powertrain = "Hybrid"
    elif "diesel" in text:
        powertrain = "Diesel"
    elif "petrol" in text or "gas" in text:
        powertrain = "Petrol"
    elif "hydrogen" in text:
        powertrain = "Hydrogen"
    else:
        powertrain = "Other"
    return pd.Series([displacement,config,powertrain])

  
updated_data[["Engine_displacement","Engine_config","PowerTrain"]]=updated_data["Engines"].apply(clean_engines)

In [109]:
updated_data

,Engines,Seats,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,Company Names_Chevrolet,...,Clean_fuels_petrol,Clean_fuels_petrolawd,Clean_fuels_petroldiesel,Clean_fuels_petrolev,Clean_fuels_petrolhybrid,Clean_fuels_pluginhybrid,New Torque,Engine_displacement,Engine_config,PowerTrain
0,V8,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,800.0,NaN,V8,Other
1,V12,5,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,NaN,V1,Other
2,1.2L Petrol,5,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,120.0,1.2,None,Petrol
3,V8,4,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,NaN,V8,Other
4,V10,2,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,560.0,NaN,V1,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,2.5L Hybrid I4,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,239.0,2.5,I4,Hybrid
1214,2.4L Turbo I4 (i-FORCE MAX Hybrid),7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,630.0,2.4,I4,Hybrid
1215,2.0L Gas / 2.0L Hybrid,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,200.0,2.0,None,Hybrid
1216,1.8L / 2.0L Hybrid,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,197.5,1.8,None,Hybrid
1217,2.5L Hybrid / Plug-in Hybrid,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,310.5,2.5,None,Hybrid

In [110]:
updated_data.drop("Engines",axis=1,inplace=True)

In [111]:
updated_data["Engine_displacement"]=updated_data["Engine_displacement"].fillna(updated_data["Engine_displacement"].mean())

In [112]:
updated_data.head()

,Seats,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,Company Names_Chevrolet,Company Names_FERRARI,...,Clean_fuels_petrol,Clean_fuels_petrolawd,Clean_fuels_petroldiesel,Clean_fuels_petrolev,Clean_fuels_petrolhybrid,Clean_fuels_pluginhybrid,New Torque,Engine_displacement,Engine_config,PowerTrain
0,2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,800.0,6.164987,V8,Other
1,5,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,6.164987,V1,Other
2,5,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,120.0,1.200000,None,Petrol
3,4,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,6.164987,V8,Other
4,2,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,560.0,6.164987,V1,Other

In [113]:
updated_data.tail()

,Seats,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,Company Names_Chevrolet,Company Names_FERRARI,...,Clean_fuels_petrol,Clean_fuels_petrolawd,Clean_fuels_petroldiesel,Clean_fuels_petrolev,Clean_fuels_petrolhybrid,Clean_fuels_pluginhybrid,New Torque,Engine_displacement,Engine_config,PowerTrain
1213,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,239.0,2.5,I4,Hybrid
1214,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,630.0,2.4,I4,Hybrid
1215,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,200.0,2.0,None,Hybrid
1216,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,197.5,1.8,None,Hybrid
1217,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,310.5,2.5,None,Hybrid

In [114]:
updated_data["Engine_config"].unique()
engine_encoded=encoder.fit_transform(updated_data[["Engine_config"]]).toarray().astype(int)

In [115]:
engine_df=pd.DataFrame(engine_encoded,columns=encoder.get_feature_names_out())

In [116]:
engine_df

,Engine_config_BOXER-4,Engine_config_I2,Engine_config_I3,Engine_config_I4,Engine_config_I6,Engine_config_INLINE-2,Engine_config_INLINE-3,Engine_config_INLINE-4,Engine_config_INLINE-6,Engine_config_ROTARY,Engine_config_V1,Engine_config_V6,Engine_config_V8,Engine_config_W16,Engine_config_WANKEL,Engine_config_None
0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1214,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1215,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1217,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [117]:
updated_data

,Seats,Company Names_ASTON MARTIN,Company Names_AUDI,Company Names_Acura,Company Names_BENTLEY,Company Names_BMW,Company Names_Bugatti,Company Names_Cadillac,Company Names_Chevrolet,Company Names_FERRARI,...,Clean_fuels_petrol,Clean_fuels_petrolawd,Clean_fuels_petroldiesel,Clean_fuels_petrolev,Clean_fuels_petrolhybrid,Clean_fuels_pluginhybrid,New Torque,Engine_displacement,Engine_config,PowerTrain
0,2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,800.0,6.164987,V8,Other
1,5,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,6.164987,V1,Other
2,5,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,120.0,1.200000,None,Petrol
3,4,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,900.0,6.164987,V8,Other
4,2,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,560.0,6.164987,V1,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,239.0,2.500000,I4,Hybrid
1214,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,630.0,2.400000,I4,Hybrid
1215,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,200.0,2.000000,None,Hybrid
1216,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,197.5,1.800000,None,Hybrid
1217,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,310.5,2.500000,None,Hybrid

In [118]:
latest_data=pd.concat([engine_df,updated_data],axis=1)
latest_data.drop("Engine_config",axis=1,inplace=True)

In [119]:
latest_data["PowerTrain"].isnull().sum()

np.int64(0)

In [120]:
latest_data["PowerTrain"]

power_converted=encoder.fit_transform(latest_data[["PowerTrain"]]).toarray().astype(int)

In [121]:
powerr_df=pd.DataFrame(power_converted,columns=encoder.get_feature_names_out())
powerr_df

,PowerTrain_Diesel,PowerTrain_Electric,PowerTrain_Hybrid,PowerTrain_Other,PowerTrain_Petrol
0,0,0,0,1,0
1,0,0,0,1,0
2,0,0,0,0,1
3,0,0,0,1,0
4,0,0,0,1,0
...,...,...,...,...,...
1213,0,0,1,0,0
1214,0,0,1,0,0
1215,0,0,1,0,0
1216,0,0,1,0,0
1217,0,0,1,0,0

In [122]:
final_data=pd.concat([powerr_df,latest_data],axis=1)
final_data.drop("PowerTrain",axis=1,inplace=True)

In [123]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 86 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   PowerTrain_Diesel                1218 non-null   int64
 1   PowerTrain_Electric              1218 non-null   int64
 2   PowerTrain_Hybrid                1218 non-null   int64
 3   PowerTrain_Other                 1218 non-null   int64
 4   PowerTrain_Petrol                1218 non-null   int64
 5   Engine_config_BOXER-4            1218 non-null   int64
 6   Engine_config_I2                 1218 non-null   int64
 7   Engine_config_I3                 1218 non-null   int64
 8   Engine_config_I4                 1218 non-null   int64
 9   Engine_config_I6                 1218 non-null   int64
 10  Engine_config_INLINE-2           1218 non-null   int64
 11  Engine_config_INLINE-3           1218 non-null   int64
 12  Engine_config_INLINE-4           1218 non-null   int64
 13  Engine_config_INLINE-6           1218 non-null   int64
 14  Engine_config_ROTARY             1218 non-null   int64
 15  Engine_config_V1                 1218 non-null   int64
 16  Engine_config_V6                 1218 non-null   int64
 17  Engine_config_V8                 1218 non-null   int64
 18  Engine_config_W16                1218 non-null   int64
 19  Engine_config_WANKEL             1218 non-null   int64
 20  Engine_config_None               1218 non-null   int64
 21  Seats                            1218 non-null   int64
 22  Company Names_ASTON MARTIN       1218 non-null   int64
 23  Company Names_AUDI               1218 non-null   int64
 24  Company Names_Acura              1218 non-null   int64
 25  Company Names_BENTLEY            1218 non-null   int64
 26  Company Names_BMW                1218 non-null   int64
 27  Company Names_Bugatti            1218 non-null   int64
 28  Company Names_Cadillac           1218 non-null   int64
 29  Company Names_Chevrolet          1218 non-null   int64
 30  Company Names_FERRARI            1218 non-null   int64
 31  Company Names_Ford               1218 non-null   int64
 32  Company Names_GMC                1218 non-null   int64
 33  Company Names_HONDA              1218 non-null   int64
 34  Company Names_HYUNDAI            1218 non-null   int64
 35  Company Names_Jaguar Land Rover  1218 non-null   int64
 36  Company Names_Jeep               1218 non-null   int64
 37  Company Names_KIA                1218 non-null   int64
 38  Company Names_KIA                1218 non-null   int64
 39  Company Names_Kia                1218 non-null   int64
 40  Company Names_LAMBORGHINI        1218 non-null   int64
 41  Company Names_MAHINDRA           1218 non-null   int64
 42  Company Names_MARUTI SUZUKI      1218 non-null   int64
 43  Company Names_MERCEDES           1218 non-null   int64
 44  Company Names_Mazda              1218 non-null   int64
 45  Company Names_Mitsubishi         1218 non-null   int64
 46  Company Names_NISSAN             1218 non-null   int64
 47  Company Names_Nissan             1218 non-null   int64
 48  Company Names_Peugeot            1218 non-null   int64
 49  Company Names_Porsche            1218 non-null   int64
 50  Company Names_ROLLS ROYCE        1218 non-null   int64
 51  Company Names_ROLLS ROYCE        1218 non-null   int64
 52  Company Names_TOYOTA             1218 non-null   int64
 53  Company Names_Tata Motors        1218 non-null   int64
 54  Company Names_Tesla              1218 non-null   int64
 55  Company Names_Toyota             1218 non-null   int64
 56  Company Names_VOLVO              1218 non-null   int64
 57  Company Names_Volkswagen         1218 non-null   int64
 58  Company Names_Volvo              1218 non-null   int64
 59  Car_names_encoded                1218 non-null   int64
 60  CC/Batery_capasity_encoded       1218 non-null   float64
 61  Hp_encoded                       1218 non-null   float64
 62  Speed_encoded                    1218 non-null   int64
 63  performance_encoded              1212 non-null   float64
 64  cleaned_Car_prices               1217 non-null   float64
 65  Clean_fuels                      1218 non-null   object
 66  Clean_fuels_cngpetrol            1218 non-null   int64
 67  Clean_fuels_diesel               1218 non-null   int64
 68  Clean_fuels_dieselhybrid         1218 non-null   int64
 69  Clean_fuels_dieselpetrol         1218 non-null   int64
 70  Clean_fuels_electric             1218 non-null   int64
 71  Clean_fuels_gashybrid            1218 non-null   int64
 72  Clean_fuels_hybrid               1218 non-null   int64
 73  Clean_fuels_hybridelectric       1218 non-null   int64
 74  Clean_fuels_hybridgaselectric    1218 non-null   int64
 75  Clean_fuels_hybridpetrol         1218 non-null   int64
 76  Clean_fuels_hybridplugin         1218 non-null   int64
 77  Clean_fuels_hydrogen             1218 non-null   int64
 78  Clean_fuels_petrol               1218 non-null   int64
 79  Clean_fuels_petrolawd            1218 non-null   int64
 80  Clean_fuels_petroldiesel         1218 non-null   int64
 81  Clean_fuels_petrolev             1218 non-null   int64
 82  Clean_fuels_petrolhybrid         1218 non-null   int64
 83  Clean_fuels_pluginhybrid         1218 non-null   int64
 84  New Torque                       1195 non-null   float64
 85  Engine_displacement              1218 non-null   float64
dtypes: float64(6), int64(79), object(1)
memory usage: 818.5+ KB

In [124]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [125]:
final_data.to_excel("CleanedCarData.xlsx",index=False)

In [126]:
final_data["cleaned_Car_prices"]=final_data["cleaned_Car_prices"].fillna(final_data["cleaned_Car_prices"].mean())

In [129]:
final_data["New Torque"]=final_data["New Torque"].fillna(final_data["New Torque"].mean())

In [131]:
final_data.isnull().sum()

PowerTrain_Diesel           0
PowerTrain_Electric         0
PowerTrain_Hybrid           0
PowerTrain_Other            0
PowerTrain_Petrol           0
                           ..
Clean_fuels_petrolev        0
Clean_fuels_petrolhybrid    0
Clean_fuels_pluginhybrid    0
New Torque                  0
Engine_displacement         0
Length: 86, dtype: int64

In [132]:
final_data.to_excel("Car.xlsx",index=False)